### PR TITLE
Recognize inline namespaces using clang's dedicated API for that

### LINKED ISSUE #2950: Inadequate recognition of inline namespaces
The following is minimized from Xcode's C++ standard library implementation.

```cpp
// namespace.h

#pragma once
#define BEGIN_NAMESPACE namespace repro { inline namespace __1 {
#define END_NAMESPACE } }
```

```cpp
// main.cc

#include "namespace.h"

BEGIN_NAMESPACE

class duration {};

END_NAMESPACE
```

```console
$ bindgen main.cc --enable-cxx-namespaces
/* automatically generated by rust-bindgen 0.70.1 */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub mod repro {
        #[allow(unused_imports)]
        use self::super::super::root;
        pub mod __1 {
            #[allow(unused_imports)]
            use self::super::super::super::root;
            #[repr(C)]
            #[derive(Debug, Copy, Clone)]
            pub struct duration {
                pub _address: u8,
            }
            #[allow(clippy::unnecessary_operation, clippy::identity_op)]
            const _: () = {
                ["Size of duration"][::std::mem::size_of::<duration>() - 1usize];
                ["Alignment of duration"][::std::mem::align_of::<duration>() - 1usize];
            };
        }
    }
}
```

Bindgen is incorrectly generating `root::repro::__1::duration` instead of `root::repro::duration`. If the 2 defines are placed into main.cc instead of namespace.h, the behavior is different.

```console
#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub mod repro {
        #[allow(unused_imports)]
        use self::super::super::root;
        #[repr(C)]
        #[derive(Debug, Copy, Clone)]
        pub struct duration {
            pub _address: u8,
        }
        #[allow(clippy::unnecessary_operation, clippy::identity_op)]
        const _: () = {
            ["Size of duration"][::std::mem::size_of::<duration>() - 1usize];
            ["Alignment of duration"][::std::mem::align_of::<duration>() - 1usize];
        };
    }
}
```

As of current master, the logic by which bindgen decides whether a namespace is inline is here:

https://github.com/rust-lang/rust-bindgen/blob/af26991da8161f4d401d0d0532a05079449e7379/bindgen/ir/context.rs#L2267-L2286

It should be using https://docs.rs/clang-sys/1.8.1/clang_sys/fn.clang_Cursor_isInlineNamespace.html instead, which I confirmed fixes this bug.

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #2950.

### CODE REVIEW

File: bindgen/clang.rs [hunk 1]
```diff
@@ -970,6 +970,11 @@ impl Cursor {
             })
         }
     }
+
+    /// Is this cursor's referent a namespace that is inline?
+    pub(crate) fn is_inline_namespace(&self) -> bool {
+        unsafe { clang_Cursor_isInlineNamespace(self.x) != 0 }
```
Comment (dtolnay) [inline bindgen/clang.rs:976]: According to https://docs.rs/clang-sys/1.8.1/clang_sys/fn.clang_Cursor_isInlineNamespace.html, this function is available in libclang 9.0 and later.

Since https://github.com/rust-lang/rust-bindgen/pull/2932, bindgen only supports libclang 9.0 or later.

**Comment by dtolnay** [comment]
CI failures appear unrelated. I sent a fix in https://github.com/rust-lang/rust-bindgen/pull/2952.

File: bindgen/clang.rs (hunk 1 above)
Comment (emilio) [reply bindgen/clang.rs:976]: Thanks for saving me the time of checking it :)

**Review by emilio — APPROVED** [review]
