### PR TITLE
fix(args): make header argument optional

### LINKED ISSUE #2677: --version no longer works without <HEADER> argument
Regressed by #2656. Found via https://github.com/mesa3d/mesa/commit/1cc26e8b6657 due to https://github.com/mesonbuild/meson/commit/0f2f87a00347

```
$ bindgen --help | fgrep -A1 -- --version
  -V, --version
          Prints the version, and exits

$ bindgen --version
error: the following required arguments were not provided:
  <HEADER>

Usage: bindgen <FLAGS> <OPTIONS> <HEADER> -- <CLANG_ARGS>...

For more information, try '--help'.

$ bindgen --version /dev/null
bindgen 0.69.0
```

Previously,
```
$ bindgen --version
bindgen 0.68.1
```

### PR DESCRIPTION
**Pull request by orhun**
fixes #2677

### CODE REVIEW

File: bindgen-cli/options.rs [hunk 1]
```diff
@@ -589,7 +590,11 @@ where
 
     let mut builder = builder();
 
-    builder = builder.header(header);
+    if let Some(header) = header {
+        builder = builder.header(header);
+    } else {
+        return Err(IoError::new(IoErrorKind::Other, "Header not found"));
```
Comment (tshepang) [inline bindgen-cli/options.rs:596]: I would not create aliases, as using the actual path is readable enough. Just a thought... feel free to ignore.

```suggestion
        return Err(io::Error::new(io::ErrorKind::Other, "Header not found"));
```

Comment (orhun) [reply bindgen-cli/options.rs]: Yeah I don't mind changing it to this.

5607d8586531650afad4852fa2bb3c4612f3fe66

**Review by erik-bershel — APPROVED** [review]

**Comment by pvdrz** [comment]
I think this is OK as a workaround but we should try to do this using clap sometime in the future.
