### PR TITLE
Translate types that were declared inside functions as opaque types.

### LINKED ISSUE #2036: Panic when a template argument refers to a function-local C++ class
Here's a case that results in a panic on the current main branch. It's reduced from some code in http://github.com/facebook/folly.

It looks like what's going on is that `Bar` is inserted into the type map twice.

### Input C/C++ Header

```C++
template<typename T>
struct Foo {};
template<typename T>
Foo<T> foo{};

void f() {
  struct Bar {
    Bar() {}
  };
  foo<Bar>;
}
```

### Bindgen Invocation

```
$ bindgen test.h -- -x c++
```

### Actual Results

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(TypeId(ItemId(13)))`,
 right: `None`', src/ir/context.rs:725:13
stack backtrace:
   0: rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: bindgen::ir::context::BindgenContext::add_item
             at ./src/ir/context.rs:725:13
   3: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty_with_id
             at ./src/ir/item.rs:1621:17
   4: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty
             at ./src/ir/item.rs:1523:9
   5: bindgen::ir::context::BindgenContext::resolve_typerefs
             at ./src/ir/context.rs:905:36
   6: bindgen::ir::context::BindgenContext::gen
             at ./src/ir/context.rs:1138:9
   7: bindgen::codegen::codegen
             at ./src/codegen/mod.rs:4184:5
   8: bindgen::Bindings::generate
             at ./src/lib.rs:2289:32
   9: bindgen::Builder::generate
             at ./src/lib.rs:1434:9
  10: bindgen::main::{{closure}}
             at ./src/main.rs:54:17
  11: std::panicking::try::do_call
             at /builddir/build/BUILD/rustc-1.49.0-src/library/std/src/panicking.rs:381:40
  12: __rust_try
  13: std::panicking::try
             at /builddir/build/BUILD/rustc-1.49.0-src/library/std/src/panicking.rs:345:19
  14: std::panic::catch_unwind
             at /builddir/build/BUILD/rustc-1.49.0-src/library/std/src/panic.rs:396:14
  15: bindgen::main
             at ./src/main.rs:53:34
  16: core::ops::function::FnOnce::call_once
             at /builddir/build/BUILD/rustc-1.49.0-src/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected Results

No panic.

### PR DESCRIPTION
**Pull request by pcwalton**
This fixes a panic with the following header:

    template<typename T>
    struct Foo {};
    template<typename T>
    Foo<T> foo{};

    void f() {
      struct Bar {
        Bar() {}
      };
      foo<Bar>;
    }

Because we don't parse the insides of function bodies, code like this could
cause us to parse a type (here, `Bar`) that we didn't see in our initial pass,
which can cause subtle problems.

Closes #2036.

### CODE REVIEW

File: tests/expectations/tests/template_instantiation_with_fn_local_type.rs [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+        ::std::mem::align_of::<Foo>(),
+        1usize,
+        concat!("Alignment of template specialization: ", stringify!(Foo))
+    );
+}
+#[repr(C)]
+#[derive(Debug, Default, Copy, Clone)]
+pub struct Bar {
+    pub _address: u8,
+}
```
Comment (emilio) [inline tests/expectations/tests/template_instantiation_with_fn_local_type.rs:34]: This looks fine, but I would expect this type to be opaque?

**Review by emilio — APPROVED** [review]
Just a question, but looks good otherwise. Thanks for digging into this and adding a test!

File: tests/expectations/tests/template_instantiation_with_fn_local_type.rs (hunk 1 above)
Comment (pcwalton) [reply tests/expectations/tests/template_instantiation_with_fn_local_type.rs:34]: What do you expect an opaque type to look like?

**Review by emilio — APPROVED** [review]
This is a bit of a wallpaper, but works for me if it unblocks you, thanks!

**Comment by emilio** [comment]
(I dug a bit more, will comment in the issue @adetaylor recently filed about a similar panic)
