### PR TITLE
Fix BitfieldUnit constructor to handle 64 bit wide bitfields on 32 bit.

### LINKED ISSUE #1639: constructor for bitfield unit with 64 bit wide bitfields fails to build on 32 bit
Input:

```c++
#include <stdint.h>

struct Test {
  uint64_t x : 56;
  uint64_t y : 8;
};
```

On 32 bit, rust-bindgen generates:

```rust
impl Test {
    ...
    #[inline]
    pub fn new_bitfield_1(
        x: u64,
        y: u64,
    ) -> __BindgenBitfieldUnit<[u8; 8usize], u64> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<
            [u8; 8usize],
            u64,
        > = Default::default();
        __bindgen_bitfield_unit.set(0usize, 56u8, {
            let x: [u32; 2usize] = unsafe { ::std::mem::transmute(x) };
            x as u64
        });
        __bindgen_bitfield_unit.set(56usize, 8u8, {
            let y: [u32; 2usize] = unsafe { ::std::mem::transmute(y) };
            y as u64
        });
        __bindgen_bitfield_unit
    }
```

This fails to compile with `non-primitive cast: '[u32; 2usize]' as 'u64'` errors.

### PR DESCRIPTION
**Pull request by heycam**
Fixes #1639.

I'm really just guessing here that this is the right fix.  I think it's OK, since we don't care about alignment for the value we pass in to the `set` function (and so it's fine to use `u64` rather than `[u32; 2]`).  We've also verified in the caller `BitfieldUnit::codegen` that the bitfield is representable as an integer.

I noticed this since `HashTable` in Gecko has bitfields like this, when I tried to land [bug 1586140](https://bugzilla.mozilla.org/show_bug.cgi?id=1586140).

### CODE REVIEW

File: src/codegen/mod.rs [hunk 1]
```diff
@@ -1216,7 +1212,9 @@ impl Bitfield {
         let bitfield_ty_layout = bitfield_ty
             .layout(ctx)
             .expect("Bitfield without layout? Gah!");
-        let bitfield_int_ty = helpers::blob(ctx, bitfield_ty_layout);
```
Comment (emilio) [inline src/codegen/mod.rs]: Hmm, so was the bitfield layout really misaligned? How does `helpers::blob` come up with `[u32; 2]` rather than `u64`? I think that's the thing to fix.

Comment (heycam) [reply src/codegen/mod.rs]: It's not misaligned.  Testing in C++ on 32 bit, I get 4 byte alignment for the bitfield and 8 byte alignment for `uint64_t`.  So it's correct in returning `[u32; 2]` for a correctly aligned 64 bit value.  It's just that we don't need to care about alignment for the argument value we're passing to `BindgenBitfieldUnit::set`.

Comment (emilio) [reply src/codegen/mod.rs]: I see, that's a nice distinction that we should probably have a test for. I'll write one before merging if you don't get to it :)

**Comment by heycam** [comment]
Test added.
