### PR TITLE
Convert *-apple-ios-sim to *-apple-ios-simulator in rust_to_clang_target

### LINKED ISSUE #3181: version 'sim' in target triple 'aarch64-apple-ios-sim' is invalid
Apple's clang 17 doesn't seem to accept `arm64-apple-ios-sim` anymore, it requires [`arm64-apple-ios-simulator`](https://github.com/search?q=repo%3Allvm%2Fllvm-project+arm64-apple-ios-simulator&type=code), causing errors such as:

    unable to generate bindings: ClangDiagnostic("error: version 'sim' in target triple 'aarch64-apple-ios-sim' is invalid\n")

### PR DESCRIPTION
**Pull request by HackerFoo**
Fixes #3181

### CODE REVIEW

File: bindgen/lib.rs [hunk 1]
```diff
@@ -704,6 +704,10 @@ fn rust_to_clang_target(rust_target: &str) -> Box<str> {
         let idx = clang_target.rfind('-').expect(TRIPLE_HYPHENS_MESSAGE);
 
         clang_target.replace_range((idx + 1).., "elf");
+    } else if clang_target.ends_with("apple-ios-sim") {
```
Comment (madsmtm) [inline bindgen/lib.rs:707]: Nit: Please make this general enough to include `*-apple-tvos-sim`, `*-apple-watchos-sim` etc.

Comment (HackerFoo) [reply bindgen/lib.rs]: Done. I cleaned up the code a bit by splitting the "triple" and reassembling it at the end.

**Review by emilio — APPROVED** [review]
Looks good, thanks!

**Comment by extrawurst** [comment]
@Emilio is it possible to cut a release with this?
