### PR TITLE
Fix bugs in --clang-macro-fallback

### LINKED ISSUE #3069: `--clang-macro-fallback` interaction with `-include`
`--clang-macro-fallback` does not work if `-include` is passed as a C flag.

For instance, given a header that would benefit from `--clang-macro-fallback`, such as:

```c
#define F(n) n
#define N F(4)
```

Then

```sh
bindgen x.h --clang-macro-fallback
```

generates the expected

```rust
pub const N: u32 = 4;
```

However, if we pass an `-include` flag, even with an empty C header, it does not anymore:

```sh
bindgen x.h --clang-macro-fallback -- -include empty.h
```

This was reduced from trying to use the `--clang-macro-fallback` feature in the Linux kernel ([mailing list post](https://lore.kernel.org/rust-for-linux/CANiq72m20pom+B9EmWO+91E8fjbMEob3JmvHRQ6UaXe_JmatfA@mail.gmail.com/) including a kernel patch to test/debug the feature), where we use a couple `-include` flags.

A possible workaround is to `#include` manually the headers at the top of the input file, and remove the `-include` flags.

Cc @jbaublitz

### LINKED ISSUE #3070: `--clang-macro-fallback` interaction with `-Wp,-MMD,file.d`
`--clang-macro-fallback`, when asking the preprocessor to generate a dependencies file, changes behavior.

For instance, given a header that would benefit from `--clang-macro-fallback`, such as:

```c
#define F(n) n
#define N F(4)
```

Then

```sh
bindgen x.h -- -Wp,-MMD,file.d
```

would generate a dependencies file like:

```makefile
x.o: x.h
```

However, if we pass `--clang-macro-fallback`, e.g.

```sh
bindgen x.h --clang-macro-fallback -- -Wp,-MMD,file.d
```

then it generates something like:

```makefile
macro_eval.o: ...abspath.../x-precompile.h ...abspath.../x.h .macro_eval.c
```

This was reduced from trying to use the `--clang-macro-fallback` feature in the Linux kernel ([mailing list post](https://lore.kernel.org/rust-for-linux/CANiq72m20pom+B9EmWO+91E8fjbMEob3JmvHRQ6UaXe_JmatfA@mail.gmail.com/) including a kernel patch to test/debug the feature).

A possible workaround may be to run `bindgen` twice.

Cc @jbaublitz

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #3069 
Closes #3070 

I've tested the fixes, but would appreciate any additional feedback on this @ojeda.

### CODE REVIEW

**Comment by jbaublitz** [comment]
I forgot to mention here that I'm doing some additional work on this so I changed it to a draft for the time being. I'll let you know when it's ready for review.

**Comment by jbaublitz** [comment]
@pvdrz Is this CI failure related to the PR? It looks unrelated to me, but I'm not sure.

**Comment by jbaublitz** [comment]
My other bindgen PR fails in the same way as this one, so I'm going to consider it unrelated. @ojeda I think this is ready for you to take a look at it if you'd like.

File: bindgen/lib.rs [hunk 1]
```diff
@@ -348,6 +348,13 @@ impl Builder {
         }
 
         // Transform input headers to arguments on the clang command line.
+        self.options.fallback_clang_args = self
+            .options
+            .clang_args
+            .iter()
+            .filter(|arg| !arg.contains("-MMD") && !arg.contains("-MD"))
```
Comment (emilio) [inline bindgen/lib.rs:355]: Should this be `starts_with`? Also shouldn't we also skip the long-version of these? (`--write-user-dependencies` / `--user-dependencies`)?

**Review by emilio — APPROVED** [review]
Please rebase, CI got fixed already IIRC.

Looks reasonable to me.

**Comment by tamird** [comment]
Would it be possible to add tests for these bugs?

**Comment by jbaublitz** [comment]
> Would it be possible to add tests for these bugs?

For the dependency generation, I am not sure how we would go about testing that only because I haven't seen any tests in the infrastructure for side effects, but it should be possible for the -include flag fix.
